baseURL: https://gobl.org
languageCode: en-us
title: GOBL

# Default content language, support en (English) / zh (Chinese) / nl (Dutch) / fr (French) / es (Spanish), default 'en'
defaultContentLanguage: en

permalinks:
  posts: /posts/:title/

paginate: 3

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs

# Site parameters
params:
  footer:
    nav:
      - title: Home
        url: /
    # - title: Posts
    #    url: /posts/
    socials:
      - icon: invopop
        url: https://invopop.com
      - icon: github
        url: https://github.com/invopop
      - icon: twitter
        url: https://twitter.com/goInvopop

  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
